frees-io/iota

modules/core/src/main/scala/iota/internal/CopKFunctionKMacros.scala
modules/core/src/main/scala/iota/internal/KListMacros.scala
modules/core/src/main/scala/iota/internal/TListMacros.scala
modules/core/src/test/scala/iotatests/CopKTests.scala
modules/core/src/test/scala/iotatests/CopTests.scala

This addresses a bug where some injection instances would fail to summon when types were equivalent but qualified differently.

Search KList/TList by type eqv instead eq

---

modules/core/src/main/scala/iota/internal/Recursion.scala
modules/core/src/main/scala/iota/internal/toolbelts.scala
modules/core/src/test/scala/iotatests/IotaReflectiveToolbeltTests.scala
modules/core/src/test/scala/iotatests/KListChecks.scala

Replace explicit recursion in toolbelt (`Node`, `TypeListParser` and `evalTree`) with recursion schemes (`NodeF`, an algebra and coalgebra and `hyloM`).

Use recursion schemes in toolbelt

---

modules/core/src/main/scala/iota/Cop.scala
modules/core/src/main/scala/iota/CopK.scala
modules/core/src/main/scala/iota/internal/Recursion.scala
modules/core/src/main/scala/iota/internal/TypeListMacros.scala
modules/core/src/main/scala/iota/internal/toolbelts.scala
modules/core/src/test/scala/iota/internal/TestTreeHelper.scala
modules/core/src/test/scala/iota/internal/TypeListEvaluationChecks.scala
modules/core/src/test/scala/iota/internal/TypeListParserChecks.scala
modules/core/src/test/scala/iotatests/FooAndFriends.scala
modules/core/src/test/scala/iotatests/IotaReflectiveToolbeltTests.scala

Reorganize toolbelt code & other misc cleanup

---

modules/core/src/main/scala/iota/internal/toolbelts.scala

This helps quite a bit when debugging failed tests :).

Show raw type trees for parser errors

---

modules/core/src/main/scala/iota/internal/toolbelts.scala
modules/core/src/test/scala/iotatests/CopKFunctionKTests.scala

Fixes an issue where poly types required an intermediate alias. Now the alias is no longer required.

Fix polytype bug

---

modules/core/src/main/scala/iota/Cop.scala
modules/core/src/main/scala/iota/CopK.scala
modules/core/src/main/scala/iota/KList.scala
modules/core/src/main/scala/iota/TList.scala
modules/core/src/main/scala/iota/internal/toolbelts.scala
modules/core/src/test/scala/iota/internal/TestTreeHelper.scala
modules/core/src/test/scala/iota/internal/TypeListEvaluationChecks.scala
modules/core/src/test/scala/iota/internal/TypeListParserChecks.scala
modules/core/src/test/scala/iotatests/KListChecks.scala
modules/core/src/test/scala/iotatests/TListChecks.scala

The ability to create a new coproduct by removing a type from an existing coproduct.
Not really convinced about `Without`, any suggestions for a better name?
I don't know if we check somewhere that the types in the coproduct are unique?
The `Pos` instances point to the first index, so I don't think it would make sense to have one type more than once.
If the types are unique, I could probably replace `filter` with something that doesn't iterate over the whole list.

Add Remove operation

---

modules/readme/src/main/tut/README.md

Addresses https://github.com/frees-io/iota/pull/55 so that the fix will be included whenever the CI bot publishes a new build.

Fix typo in the source for the README.me file

---

README.md
build.sbt
modules/bench/src/codegen/scala/codegen.scala
modules/core/src/main/scala/iota/Cop.scala
modules/core/src/main/scala/iota/CopK.scala
modules/readme/src/main/tut/README.md

This is the minimum amount of work to bump to cats 1.0.0 and provide compatibility with `cats.Inject` and `cats.InjectK`.
New tests should be added to verify that the cats syntax can be used for injections. The packaging/implicits may need to be adjusted to support this.

Bump cats to 1.0.0-MF; adjust Injects

---

modules/core/src/main/scala/iota/internal/toolbelts.scala
modules/core/src/test/scala/iotatests/FreeCopKTests.scala
project/ProjectPlugin.scala

This addresses a recently discovered issue that affects the Freestyle core libraries.

Ensure Idents are qualified/attributed when creating FastFunctionKs

---

modules/core/src/main/scala/iota/internal/CopKFunctionKMacros.scala
modules/core/src/main/scala/iota/internal/ProductMacros.scala

`NonEmptyList.one` is a bit faster. See https://github.com/typelevel/cats/pull/1707.

Use NEL.one instead of NEL.of

---

modules/core/src/main/scala/iota/Cop.scala

The Scalaz version is missing a few important methods. This fixes that!

Fix missing inject methods for iotaz

---

README.md
build.sbt
docs/cats.md
docs/scalaz.md
docs/scalaz.md.bak
modules/core/src/main/scala/iota/Cop.scala
modules/core/src/main/scala/iota/CopK.scala
modules/core/src/main/scala/iota/internal/CopKFunctionKMacros.scala
modules/core/src/main/scala/iota/internal/toolbelts.scala
modules/docs/src/main/tut/cats.md
modules/docs/src/main/tut/scalaz.md
modules/examples-scalaz/src/main/scala/example/FreeExample.scala
modules/readme/src/main/tut/README.md
modules/tests/src/test/scala/iotatests/CopKFunctionKTests.scala
modules/tests/src/test/scala/iotatests/CopKTests.scala
modules/tests/src/test/scala/iotatests/CopTests.scala
project/ProjectPlugin.scala

There are a few remaining fixes in the tests to get the build green, but:
- Split the README into separate docs for Cats / Scalaz
- Add guards for alerting users of the slight issue with Scalaz's variances on `NaturalTransformation`.
- "Fix" Scalaz support
**_Fixing Scalaz support_**
There was one big issue related to type inferencing for the parameters on `CopK.NaturalTransformation.of/summon`. After a bit of debugging while at SBTB I've sorted out what seems to be the best solution.
The short story is that the variances on Scalaz's NaturalTransformation cause the typer to simply assume `Nothing` (or use an existential type) instead of computing a type tag. A potential solution was posted on SO several years ago, but this doesn't work for this use case.
For the time being, Scalaz users …

Split README / Fix Scalaz

---

project/ProjectPlugin.scala
project/ScalacOptionsPlugin.scala

- Moves scalac options to a plugin
- Adds more thorough options for Scala 2.12

Move scalac options to a "plugin"

---

modules/core/src/main/scala/iota/evidence.scala
modules/core/src/main/scala/iota/internal/EvidenceMacros.scala
modules/core/src/main/scala/iota/syntax/helpers.scala
modules/core/src/main/scala/iota/syntax/package.scala
modules/examples-cats/src/main/scala/example/Evidence.scala

This adds the ability to summon a coproduct of evidence, searching for types according to the TList parameter.
I hope to follow up by adding `AllK` evidence and eventually new higher kinded coproduct and product implementations with the respective evidence summoning support.

Add first item evidence for CopK

---

modules/core/src/main/scala/iota/CopH.scala
modules/core/src/main/scala/iota/evidence/evidence.scala
modules/core/src/main/scala/iota/internal/EvidenceMacros.scala
modules/tests/src/test/scala/iotatests/Evidence.scala

- Adds CopH, a coproduct for types of shape `H[_[_]]`.
- Adds FirstH evidence for summoning shape `H[_[_]]`
- Adds a basic demo
Additionally there was a discussion on what to name different shapes. I think we'll ultimately follow:
```
name    shape
A       T
K       T[_]
H       T[_[_]]
HK      T[_[_], _]
```

Add support for coproducts of H functors

---

modules/bench/src/codegen/scala/codegen.scala
modules/core/src/main/scala/iota/CopK.scala
modules/core/src/main/scala/iota/syntax/helpers.scala
modules/examples-cats/src/main/scala/example/FreeErrorAlgebra.scala
modules/examples-cats/src/main/scala/example/NestedCoproducts.scala
modules/tests/src/test/scala/iotatests/FreeCopKTests.scala

Properly qualify the bounds for `CopK.Inject`.

Fix bounds for CopK.Inject

---

CONTRIBUTING.md
LICENSE
project/ProjectPlugin.scala
project/plugins.sbt

The problem was caused because the `orgEnforcedFilesSetting` was overridden to `Nil`.
This PR should fix it, hence the bot will keep up-to-date the README, the License, etc.

Fixes Badges

---

CONTRIBUTING.md
LICENSE
project/ProjectPlugin.scala
project/plugins.sbt
version.sbt

Releases 0.3.5. Notably, this includes:
- selectively summoning evidence using coproducts
- a Scalacheck module
- CopH, a coproduct of shape `T[_[_]]`

Release 0.3.5

---

.travis.yml
project/ProjectPlugin.scala

This PR provides a new CI pipeline:
* Tests (for both Scala 2.11 and 2.12).
* Validate: where files and docs are validated.
* Deploy: this stage only will run if the previous stages result successfully.

Improves CI Pipeline

---

build.sbt
project/ProjectPlugin.scala

With these changes, only scalajs is shown in the dependency updates report:
```bash
sbt:iota> dependencyUpdates
[info] No dependency updates found for iotaz-core
[info] No dependency updates found for iota
[info] No dependency updates found for iota-examples-scalaz
[info] No dependency updates found for iota-core
[info] Found 3 dependency updates for iota-core
[info]   org.scala-js:scalajs-compiler:plugin->default(compile) : 0.6.20 -> 0.6.22
[info]   org.scala-js:scalajs-library                           : 0.6.20 -> 0.6.22
[info]   org.scala-js:scalajs-test-interface:test               : 0.6.20 -> 0.6.22
[info] Found 3 dependency updates for iotaz-core
[info]   org.scala-js:scalajs-compiler:plugin->default(compile) : 0.6.20 -> 0.6.22
[info]   org.scala-js:scalajs-library …
```

Filter out some deps from the updates report

---

modules/core/src/main/scala/iota/internal/TypeListMacros.scala

If some project is compiled with `-Yno-imports`, there is no `Int` in scope. This leads to a silent error and implicit not found, requires importing scala.Int explicitly to actually get things to work.
In this PR I added fully qualified type replacing `Int` in macros to `scala.Int` which solves the problem.
I am not sure if or how this change should be tested. I didn't manage to unimport Int. Maybe `-Yno-imports` should be added for tests project?

Add full path for scala.Int type to macros

---

modules/core/src/main/scala/iota/Cop.scala
modules/core/src/main/scala/iota/CopH.scala
modules/core/src/main/scala/iota/CopK.scala
modules/core/src/main/scala/iota/Prod.scala
modules/tests/src/test/scala/iotatests/HashcodeTests

Hashcode implementation is missing for `CopK` and other classes. This means that they use reference equality in maps. If I inject the same value to a coproduct twice, hashcode will not be equals causing problems when using maps.
Sorry for rather poor tests but I don't have time now to prepare something pretty.

Implement hashcode for all data types

---

.travis.yml

https://github.com/travis-ci/travis-ci/issues/10290#issuecomment-432331802
> oraclejdk8 is not preinstalled on Xenial anymore, and cannot be retrieved from Oracle itself anymore. We'd suggest using either openjdk, or the currently supported Oracle JDK.

use openjdk8 instead of oraclejdk8
